"""empty message

Revision ID: 376a5b777546
Revises: 68c53204d90a
Create Date: 2023-07-14 18:26:25.353657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376a5b777546'
down_revision = '68c53204d90a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###
