"""empty message

Revision ID: 407ab4a39beb
Revises: 03ac66a5be47
Create Date: 2023-07-01 19:24:10.927272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407ab4a39beb'
down_revision = '03ac66a5be47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owned_courses',
    sa.Column('owned_id', sa.Integer(), nullable=False),
    sa.Column('owned_by', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['owned_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('owned_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owned_courses')
    # ### end Alembic commands ###
