"""empty message

Revision ID: 43086788f217
Revises: 
Create Date: 2023-06-25 13:14:42.510875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43086788f217'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('resume', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('panel_users',
    sa.Column('panel_userid', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('profile_picture', sa.String(length=300), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_admin', sa.Integer(), nullable=False),
    sa.Column('is_teacher', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('panel_userid')
    )
    with op.batch_alter_table('panel_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_panel_users_email'), ['email'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_title', sa.String(length=300), nullable=True),
    sa.Column('course_description', sa.String(length=2000), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('course_thumbnail', sa.String(length=200), nullable=True),
    sa.Column('course_price', sa.Integer(), nullable=True),
    sa.Column('course_category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['panel_users.panel_userid'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('featured_courses',
    sa.Column('featured_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('featured_id')
    )
    op.create_table('lectures',
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('lecture_number', sa.Integer(), nullable=False),
    sa.Column('lecture_title', sa.String(length=300), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('lecture_description', sa.String(length=2000), nullable=True),
    sa.Column('lecture_video', sa.String(length=200), nullable=True),
    sa.Column('lecture_type', sa.String(length=100), nullable=True),
    sa.Column('lecture_duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.PrimaryKeyConstraint('lecture_id', 'lecture_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lectures')
    op.drop_table('featured_courses')
    op.drop_table('courses')
    op.drop_table('users')
    with op.batch_alter_table('panel_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_panel_users_email'))

    op.drop_table('panel_users')
    op.drop_table('applications')
    # ### end Alembic commands ###
