"""empty message

Revision ID: 472d6453b372
Revises: 991f632f122c
Create Date: 2023-07-27 15:52:51.897742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472d6453b372'
down_revision = '991f632f122c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_withdrawals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_withdrawals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
