"""empty message

Revision ID: beac7d1b7ae6
Revises: cfe432055b8e
Create Date: 2023-07-04 10:58:33.017791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beac7d1b7ae6'
down_revision = 'cfe432055b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_no', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('stripe_id', sa.String(length=255), nullable=True))
        batch_op.drop_index('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)
        batch_op.drop_column('stripe_id')
        batch_op.drop_column('address')
        batch_op.drop_column('phone_no')

    # ### end Alembic commands ###
